### ISSUE TITLE
How to switch accounts?

### ISSUE THREAD

**Issue by shihabdider** [pimalaya/himalaya-vim#10]
Is there any (convenient) way to switch the account that's being used from within himalaya-vim? E.g using the `:Himalaya` command with the account name to open the envelopes for that account (as with the `-a account` flag on the CLI).

**Comment by soywod** [comment]
Duplicate https://github.com/pimalaya/himalaya-vim/issues/8, the feature does not exist yet. You can subscribe to it in order to get a notification wheneven it is ready!
