### ISSUE TITLE
Support `fzf-lua` as a folder picker

### ISSUE THREAD

**Issue by parisni** [pimalaya/himalaya-vim#15]
Hey, I am using `ibhagwan/fzf-lua` instead of `junegunn/fzf.vim`. Sounds like it does not works the same ? 

after setting:

```vim
let g:himalaya_folder_picker = 'fzf'
```

I get the bellow  error:
```
Error detected while processing function <lambda>71[1]..<SNR>39_on_exit[9]..<lambda>68[1]..<SNR>36_on_json_data[1]..<lambda>67[1]..<SNR>35_op
en_picker[13]..himalaya#domain#folder#pickers#fzf#select:
line    1:
E117: Unknown function: fzf#run
```

thanks for your insights

**Comment by soywod** [comment]
Hey, indeed the `fzf` backend expects `junegunn/fzf.vim`. Feel free to propose a PR in order to support `fzf-lua`.
