### ISSUE TITLE
Support searching for emails

### ISSUE THREAD

**Issue by lyz-code** [pimalaya/himalaya-vim#16]
Himalaya does support [email searching](https://github.com/pimalaya/himalaya/issues/524), it would be super nice to be able to do it within the vim plugin

**Comment by soywod** [comment]
Yes indeed, it has been done for the [Emacs plugin](https://github.com/dantecatalfamo/himalaya-emacs/blob/934e8f8741e3cfff577d7119eceb2cfdb7cff6f3/himalaya-envelope.el#L162-L168) so it could definitely be done for Vim as well.

**Comment by parisni** [comment]
not sure if this is the topic, but I have been able to search with this keymap in lazyvim
```
      { "<leader>m/", "<plug>(himalaya-set-list-envelopes-query)", desc = "Query" },

```

**Comment by lyz-code** [comment]
Thank you so much @parisni  I don't know how I missed that, it's even in the docs (╥﹏╥)

For those of you that are reading and need some guidance on how to do queries, you can see it in `himalaya envelope list --help`. It contains the next content:

## Searching emails

You can use the `g/` binding from within nvim to search for emails. The query syntax supports filtering and sorting query.

### Filters

A filter query is composed of operators and conditions. There is 3 operators and 8 conditions:

- `not <condition>`: filter envelopes that do not match the condition
- `<condition> and <condition>`: filter envelopes that match both conditions
- `<condition> or <condition>`: filter envelopes that match one of the conditions
- `ate <yyyy-mm-dd>`: filter envelopes that match the given date
- `before <yyyy-mm-dd>`: filter envelopes with date strictly before the given one
- `after <yyyy-mm-dd>`: filter envelopes with date stricly after the given one
- `from <pattern>`: filter envelopes with senders matching the given pattern
- `o <pattern>`: filter envelopes with recipients matching the given pattern
- `subject <pattern>`: filter envelopes with subject matching the given pattern
- `body <pattern>`: filter envelopes with text bodies matching the given pattern
- `flag <flag>`: filter envelopes matching the given flag

### Sorting 
A sort query starts by "order by", and is composed of kinds and orders. There is 4 kinds and 2 orders:

- `date [order]`: sort envelopes by date
- `from [order]`: sort envelopes by sender
- `to [order]`: sort envelopes by recipient
- `subject [order]`: sort envelopes by subject
- `<kind> asc`: sort envelopes by the given kind in ascending order
- `<kind> desc`: sort envelopes by the given kind in descending order

### Examples

`subject foo and body bar`: filter envelopes containing "foo" in their subject and "bar" in their text bodies
`order by date desc subject`: sort envelopes by descending date (most recent first), then by ascending subject
`subject foo and body bar order by date desc subject`: combination of the 2 previous examples


If you write a wrong query [the plugin so far will crash](https://github.com/pimalaya/himalaya-vim/issues/19)

**Comment by parisni** [comment]
You are welcome. After all most of my config comes from your blue book ¯\_(ツ)_/¯

**Comment by lyz-code** [comment]
Lol @parisni I did not see that one coming. I'm glad you're using it!
